[modules]
autoload=yes

; Asterisk spams the log with scary ERROR messages for all modules that are not going to be loaded 🫠
noload=res_stun_monitor
noload=res_phoneprov
noload=chan_iax2
noload=chan_console
noload=res_hep
noload=res_pjsip_notify
noload=res_ari
noload=app_confbridge
noload=app_agent_pool
noload=res_parking
noload=res_calendar
noload=cdr_sqlite3_custom
noload=cel_sqlite3_custom
noload=cel_manager
noload=cdr_manager
noload=cdr_csv
noload=pbx_lua
noload=res_http_media_cache
noload=app_festival
noload=app_amd
noload=chan_unistim
noload=app_alarmreceiver
noload=app_voicemail_imap
noload=res_prometheus
noload=app_followme
noload=pbx_dundi
noload=pbx_ael
noload=app_queue
noload=app_pag
